@startjson JSON-Diagramm Messdaten

{
    "2100": {
        "azimut": ["0,5,10,15,20,..."],
        "elevation": ["-10,-5,0,5,10,..."],
        "gain": ["1.4,3.2,-0.7,0.3,5.2,..."]
    },
    "2200": {
        "azimut": ["0,5,10,15,20,..."],
        "elevation": ["-10,-5,0,5,10,..."],
        "gain": ["3.5,1.9,0.2,-3.6,1.8,..."]
    },
    "...": {
        "azimut": [],
        "elevation": [],
        "gain": []
    }
}

@endjson